#!/usr/bin/env bash
# RUN_ONCE.sh — bootstrap for PSF Workbench's Electron UI on a fresh dev machine.
#
# Idempotent. Safe to re-run. Won't reinstall things that are already correct.
#
# What it does:
#   1. Verifies Linux + apt (this script targets Debian/Ubuntu hosts for now;
#      the Workbench's Day-1 target audience is on Ubuntu 24.04).
#   2. Installs Node.js LTS via NodeSource if `node` is missing or too old.
#   3. Runs `npm ci` (or `npm install` on first run) inside ui/ to fetch
#      Electron and the small set of UI deps.
#   4. Drops a `workbench-ui` launcher script at the repo root that runs the
#      Electron app.
#   5. Smoke-tests by checking that `node`, `npm`, and the Electron binary
#      all resolve.
#
# It does NOT:
#   - Install Docker, Distrobox, pixi, or the AIC eval image. Those are
#     handled separately (and eventually by Workbench itself, post-AIC).
#   - Pull any AIC adapter content. The intrinsic-aic adapter pack ships
#     with the repo.
#   - Make any system-wide config changes outside of installing Node.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UI_DIR="$REPO_DIR/ui"
NODE_MAJOR_REQUIRED=20  # Electron 30+ wants Node 20+; we target Node 22 LTS.

# ── output helpers ────────────────────────────────────────────────────
c_dim() { printf '\033[2m%s\033[0m' "$*"; }
c_good() { printf '\033[32m%s\033[0m' "$*"; }
c_warn() { printf '\033[33m%s\033[0m' "$*"; }
c_bad() { printf '\033[31m%s\033[0m' "$*"; }
say() { echo "[run-once] $*"; }
ok()  { echo "[run-once] $(c_good "✓") $*"; }
warn(){ echo "[run-once] $(c_warn "!") $*"; }
bad() { echo "[run-once] $(c_bad "✗") $*" >&2; }
die() { bad "$*"; exit 1; }

# ── 1. host check ─────────────────────────────────────────────────────
say "checking host"

if [[ "$(uname -s)" != "Linux" ]]; then
  die "This bootstrap targets Linux. macOS/Windows support comes later via Electron packaging."
fi

if ! command -v apt >/dev/null 2>&1; then
  die "This bootstrap currently requires apt (Debian/Ubuntu). Other distros: install Node 20+ manually, then run \`cd ui && npm install\`."
fi

ok "Linux + apt detected"

# ── 2. Node.js ────────────────────────────────────────────────────────
say "checking Node.js"

need_node_install=false
if ! command -v node >/dev/null 2>&1; then
  need_node_install=true
  warn "node not found"
else
  current_major="$(node -p 'process.versions.node.split(".")[0]')"
  if (( current_major < NODE_MAJOR_REQUIRED )); then
    need_node_install=true
    warn "node $(node -v) found, but Workbench's UI needs >= $NODE_MAJOR_REQUIRED"
  else
    ok "node $(node -v) ready"
  fi
fi

if $need_node_install; then
  say "installing Node.js LTS via NodeSource"
  say "(this needs sudo; you'll be prompted)"

  # NodeSource setup — the canonical way to install a current Node on Ubuntu.
  # Reference: https://github.com/nodesource/distributions
  curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
  sudo apt install -y nodejs

  ok "node $(node -v) installed"
fi

# Sanity: npm should come with node
if ! command -v npm >/dev/null 2>&1; then
  die "npm missing after Node install. Try: sudo apt install --reinstall nodejs"
fi
ok "npm $(npm -v) ready"

# ── 3. UI deps ────────────────────────────────────────────────────────
say "installing UI dependencies"

if [[ ! -f "$UI_DIR/package.json" ]]; then
  die "ui/package.json not found at $UI_DIR. The repo may be incomplete."
fi

cd "$UI_DIR"
# Prefer `npm ci` (faster, deterministic) when the lockfile is in sync
# with package.json. If not — typically because deps were added to
# package.json without regenerating the lockfile — fall back to
# `npm install` which will reconcile the two.
if [[ -f "package-lock.json" ]] && npm ci --no-audit --no-fund 2>/dev/null; then
  :  # ci succeeded, nothing more to do
else
  if [[ -f "package-lock.json" ]]; then
    say "lockfile out of sync with package.json — running 'npm install' to reconcile"
  fi
  npm install --no-audit --no-fund
fi
cd "$REPO_DIR"

ok "Electron + UI deps installed under ui/node_modules"

# ── 4. launcher ───────────────────────────────────────────────────────
LAUNCHER="$REPO_DIR/workbench-ui"
say "writing launcher: $LAUNCHER"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by RUN_ONCE.sh. Re-run RUN_ONCE.sh if anything breaks.
set -euo pipefail
REPO_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"

# Vision-policy runtime defaults (AIC-Submission):
# - capture frames/offsets for local training
# - optionally enable model inference if a model file exists
export AIC_VISION_CAPTURE_DIR="\${AIC_VISION_CAPTURE_DIR:-/ws_aic/src/aic_policy_capture}"
export AIC_VISION_MODEL_ENABLE="\${AIC_VISION_MODEL_ENABLE:-0}"
export AIC_VISION_MODEL_PATH="\${AIC_VISION_MODEL_PATH:-/ws_aic/src/aic_policy/data/models/vision_offset_model.npz}"

# Ensure local capture dir exists when host path is used.
mkdir -p "\${AIC_VISION_CAPTURE_DIR}" 2>/dev/null || true

exec "\$REPO_DIR/ui/node_modules/.bin/electron" "\$REPO_DIR/ui" "\$@"
EOF
chmod +x "$LAUNCHER"
ok "launcher ready: ./workbench-ui"

# ── 5. smoke test ─────────────────────────────────────────────────────
say "smoke-testing"

ELECTRON_BIN="$UI_DIR/node_modules/.bin/electron"
if [[ ! -x "$ELECTRON_BIN" ]]; then
  die "electron binary not found at $ELECTRON_BIN — npm install may have failed"
fi

# Electron's --version flag exits cleanly without opening a window.
"$ELECTRON_BIN" --version >/dev/null
ok "electron $($ELECTRON_BIN --version) ready"

# ── done ──────────────────────────────────────────────────────────────
echo
echo "$(c_good "All set.") Launch the UI with:"
echo
echo "    ./workbench-ui"
echo
echo "$(c_dim "(re-run this script any time deps drift; it is idempotent.)")"
